// DO NOT EDIT - Auto-generated by Style Dictionary
// Generated at: 2025-11-27T21:33:28.539Z

import 'package:flutter/material.dart';

/// Design system color tokens
abstract class DsColors {
  static const Color primary50 = Color(0xFFEFF6FF);
  static const Color primary100 = Color(0xFFDBEAFE);
  static const Color primary200 = Color(0xFFBFDBFE);
  static const Color primary300 = Color(0xFF93C5FD);
  static const Color primary400 = Color(0xFF60A5FA);
  static const Color primary500 = Color(0xFF3B82F6);
  static const Color primary600 = Color(0xFF2563EB);
  static const Color primary700 = Color(0xFF1D4ED8);
  static const Color primary800 = Color(0xFF1E40AF);
  static const Color primary900 = Color(0xFF1E3A8A);
  static const Color secondary50 = Color(0xFFFAF5FF);
  static const Color secondary100 = Color(0xFFF3E8FF);
  static const Color secondary200 = Color(0xFFE9D5FF);
  static const Color secondary300 = Color(0xFFD8B4FE);
  static const Color secondary400 = Color(0xFFC084FC);
  static const Color secondary500 = Color(0xFFA855F7);
  static const Color secondary600 = Color(0xFF9333EA);
  static const Color secondary700 = Color(0xFF7E22CE);
  static const Color secondary800 = Color(0xFF6B21A8);
  static const Color secondary900 = Color(0xFF581C87);
  static const Color neutral50 = Color(0xFFFAFAFA);
  static const Color neutral100 = Color(0xFFF4F4F5);
  static const Color neutral200 = Color(0xFFE4E4E7);
  static const Color neutral300 = Color(0xFFD4D4D8);
  static const Color neutral400 = Color(0xFFA1A1AA);
  static const Color neutral500 = Color(0xFF71717A);
  static const Color neutral600 = Color(0xFF52525B);
  static const Color neutral700 = Color(0xFF3F3F46);
  static const Color neutral800 = Color(0xFF27272A);
  static const Color neutral900 = Color(0xFF18181B);
  static const Color success50 = Color(0xFFF0FDF4);
  static const Color success500 = Color(0xFF22C55E);
  static const Color success700 = Color(0xFF15803D);
  static const Color warning50 = Color(0xFFFFFBEB);
  static const Color warning500 = Color(0xFFF59E0B);
  static const Color warning700 = Color(0xFFB45309);
  static const Color error50 = Color(0xFFFEF2F2);
  static const Color error500 = Color(0xFFEF4444);
  static const Color error700 = Color(0xFFB91C1C);
  static const Color semanticBackground = Color(0xFFFAFAFA);
  static const Color semanticSurface = Color(0xFFFFFFFF);
  static const Color semanticText = Color(0xFF18181B);
  static const Color semanticTextMuted = Color(0xFF71717A);
  static const Color semanticBorder = Color(0xFFE4E4E7);
}

/// Design system spacing tokens
abstract class DsSpacing {
  static const double space0 = 0;
  static const double space1 = 4;
  static const double space2 = 8;
  static const double space3 = 12;
  static const double space4 = 16;
  static const double space5 = 20;
  static const double space6 = 24;
  static const double space8 = 32;
  static const double space10 = 40;
  static const double space12 = 48;
  static const double space16 = 64;
  static const double space20 = 80;
  static const double space24 = 96;
}

/// Design system typography tokens
abstract class DsTypography {
  static const String fontFamilySans = 'Inter';
  static const String fontFamilyMono = 'JetBrains Mono';
  static const double fontSizeXs = 12;
  static const double fontSizeSm = 14;
  static const double fontSizeBase = 16;
  static const double fontSizeLg = 18;
  static const double fontSizeXl = 20;
  static const double fontSize2xl = 24;
  static const double fontSize3xl = 30;
  static const double fontSize4xl = 36;
  static const double fontSize5xl = 48;
  static const FontWeight fontWeightNormal = FontWeight.w400;
  static const FontWeight fontWeightMedium = FontWeight.w500;
  static const FontWeight fontWeightSemibold = FontWeight.w600;
  static const FontWeight fontWeightBold = FontWeight.w700;
  static const double lineHeightTight = 1.25;
  static const double lineHeightNormal = 1.5;
  static const double lineHeightRelaxed = 1.75;
}

/// Design system border radius tokens
abstract class DsBorderRadius {
  static const double none = 0;
  static BorderRadius noneAll = BorderRadius.circular(0);
  static const double sm = 4;
  static BorderRadius smAll = BorderRadius.circular(4);
  static const double md = 8;
  static BorderRadius mdAll = BorderRadius.circular(8);
  static const double lg = 12;
  static BorderRadius lgAll = BorderRadius.circular(12);
  static const double xl = 16;
  static BorderRadius xlAll = BorderRadius.circular(16);
  static const double n2xl = 24;
  static BorderRadius n2xlAll = BorderRadius.circular(24);
  static const double full = 9999;
  static BorderRadius fullAll = BorderRadius.circular(9999);
}

/// Design system shadow tokens
abstract class DsShadows {
  // sm: Use BoxShadow or BoxDecoration for shadow implementation
  // md: Use BoxShadow or BoxDecoration for shadow implementation
  // lg: Use BoxShadow or BoxDecoration for shadow implementation
  // xl: Use BoxShadow or BoxDecoration for shadow implementation
}

/// Design system transition/animation duration tokens
abstract class DsTransitions {
  static const Duration fast = Duration(milliseconds: 150);
  static const Duration normal = Duration(milliseconds: 200);
  static const Duration slow = Duration(milliseconds: 300);
}
